Repository xpsi-group/xpsi, pull requests merged in 2022-09, with the labels that each got.

#102 Updating setup.py
  docs/source/install.rst
  setup.py
Labels: enhancement, hackweek2022

#103 Fixes #58
  xpsi/Photosphere.py
  xpsi/global_imports.py
Labels: bug, hackweek2022

#111 Installation instructions for Snellius, Lisa and CALMIP
  docs/source/HPC_systems.rst
  docs/source/SURFsara_systems.rst
  docs/source/index.rst
Labels: documentation, hackweek2022

#114 Sphinx installation instructions for python2 added to `install.rst`
  docs/source/install.rst
Labels: documentation, hackweek2022

#118 Parameter not present in subspace indicated in error message displayed
  xpsi/ParameterSubspace.py
Labels: enhancement, hackweek2022

#117 Clarifying errors in instrument class and variable 'array' name change
  xpsi/Instrument.py
Labels: hackweek2022

#116 Tests for Spacetime class
  docs/source/install.rst
  xpsi/Spacetime.py
  xpsi/tests/test_spacetime.py
Labels: enhancement, hackweek2022

#128 Helios installation instruction added.
  docs/source/HPC_systems.rst
Labels: hackweek2022

#132 119 example jobs page on docs is outdated
  docs/source/example_job.rst
Labels: documentation, hackweek2022

#124 Option added to show all the credible intervals for different runs id…
  xpsi/PostProcessing/_corner.py
Labels: hackweek2022

#127 unit tests for Instrument class
  xpsi/tests/test_instrument.py
Labels: hackweek2022

#152 Added script for CI tests
  .github/workflows/ci_tests.yml
  examples/examples_fast/Modules/CustomPhotosphere.py
Labels: enhancement, hackweek2022

#147 Install page updated
  basic_environment.yml
  docs/source/install.rst
Labels: documentation, hackweek2022

#148 Limitation on number of plots set to 9 due to prevent plot overcrowding.
  xpsi/PostProcessing/_postprocessor.py
Labels: enhancement, hackweek2022

#154 Duplicate section, bashrc & profile examples removed. Mac comms refined
  docs/source/install.rst
Labels: documentation, hackweek2022

#153 Added badges to readme
  README.rst
Labels: enhancement, hackweek2022
