Repository xpsi-group/xpsi, pull requests merged in 2023-02, with the labels that each got.

#228 Adjusting modelling tutorial plot function for pcolormesh
  docs/source/Modeling.ipynb
Labels: python3, hackweek2023

#233 Moving conda install commands to one line to speed up build
  .github/workflows/build_docs.yml
Labels: documentation, tests, jossreview

#236 234 debugging projection tool
  xpsi/utilities/ProjectionTool.py
Labels: bugfix

#240 239 extra ticks options for Plot functions in the tutorials
  docs/source/Hot_region_complexity.ipynb
  docs/source/Instrument_synergy.ipynb
  docs/source/Modeling.ipynb
  docs/source/Modeling_without_statistics.ipynb
Labels: documentation, python3, hackweek2023

#237 Make mandatory channel_edges argument in CustomInstrument
  docs/source/Instrument_synergy.ipynb
  docs/source/Modeling.ipynb
  examples/examples_fast/Modules/CustomInstrument.py
  examples/examples_fast/Modules/main.py
  examples/examples_modeling_tutorial/TestRun_BB.py
  examples/examples_modeling_tutorial/TestRun_Num.py
  examples/examples_modeling_tutorial/TestRun_NumBeam.py
Labels: documentation, hackweek2023

#250 Adding names of parameters across diagonal in corner plots
  xpsi/PostProcessing/_corner.py
Labels: enhancement, python3, hackweek2023

#252 Added warning to front page of docs
  docs/source/index.rst
  docs/source/intro.rst
Labels: documentation, hackweek2023

#241 HPC installation instructions for Snellius+Helios updated for python3
  docs/source/Example_job.rst
  docs/source/HPC_systems.rst
Labels: python3, hackweek2023

#246 Py3 redo the intro pages install page 205
  diagnosis_environment.yml
  docs/source/install.rst
  environment.yml
Labels: documentation, python3, hackweek2023

#272 `np.int` changed to `np.int32`
  xpsi/Data.py
Labels: bugfix

#273 Added DOI to JOSS bib file
  joss/xpsijoss.bib
Labels: documentation

#280 Updates to JOSS paper on main branch
  joss/paper.md
  joss/xpsijoss.bib
Labels: documentation
