Repository xpsi-group/xpsi, pull requests merged in 2024-12, with the labels that each got.

#394 Remove unused modules
  examples/examples_fast/Modules/CustomInstrument.py
  examples/examples_fast/Modules/CustomPhotosphere.py
  examples/examples_fast/Modules/CustomPrior.py
  examples/examples_fast/Modules/CustomSignal.py
  examples/examples_fast/Modules/main.py
  examples/examples_modeling_tutorial/TestRun_AMXP.py
  examples/examples_modeling_tutorial/TestRun_BB.py
  examples/examples_modeling_tutorial/TestRun_Num.py
  examples/examples_modeling_tutorial/TestRun_NumBeam.py
  examples/examples_modeling_tutorial/TestRun_Pol.py
  examples/examples_modeling_tutorial/TestRun_PolNum_split_1spot.py
  examples/examples_modeling_tutorial/TestRun_PolNum_split_inference.py
  examples/examples_modeling_tutorial/ixpeobssim/simulate_amsp_xpsi.py
  examples/examples_modeling_tutorial/modules/CustomHotRegion_Beaming.py
  examples/examples_modeling_tutorial/modules/CustomPhotosphere.py
  examples/examples_modeling_tutorial/modules/CustomPrior_Beaming.py
  examples/examples_module_generator/_auto_modules/CustomInstrument.py
  examples/examples_module_generator/_auto_modules/CustomInterstellar.py
  examples/examples_module_generator/_auto_modules/CustomSignal.py
  setup.py
Labels: enhancement

#422 Remove py2 documentation from build docs action
  .github/workflows/build_docs.yml
  README.rst
  docs/source/intro.rst
Labels: hackweek2024

#457 SBI files and tutorial
  docs/source/index.rst
  docs/source/install.rst
  docs/source/x_p_sbi.ipynb
  xpsi/SBI_wrapper.py
  xpsi/__init__.py
  xpsi/utilities/Example_CNNs.py
Labels: enhancement, hackweek2024

#462 Solve #460 - Added return/enter at the end of the rst file
  docs/source/index.rst
Labels: bugfix

#464 uploading rst file for SBI_wrapper
  .github/workflows/build_docs.yml
  docs/source/SBI_wrapper.rst
  docs/source/Start_here.rst
  xpsi/SBI_wrapper.py
Labels: bugfix, hackweek2024

#486 Bugfix #485
  xpsi/PostProcessing/_residual.py
  xpsi/utilities/BackgroundTools.py
Labels: bugfix

#494 Corrected deepcopy bug on instrument and data
  xpsi/Signal.py
Labels: bugfix
