Repository xpsi-group/xpsi, pull requests merged in 2025-05, with the labels that each got.

#521 Using Latin hypercube sampler for `Prior.draw`
  .github/workflows/ci_tests.yml
  CHANGELOG.rst
  docs/source/conf.py
  examples/examples_fast/Modules/main.py
  examples/examples_fast/Modules/main_IS_likelihood.py
  examples/examples_fast/Modules/main_IS_prior.py
  examples/examples_fast/Sampling.ipynb
  examples/examples_modeling_tutorial/TestRun_BB.py
  examples/examples_modeling_tutorial/TestRun_Num.py
  examples/examples_modeling_tutorial/TestRun_NumBeam.py
  examples/examples_modeling_tutorial/TestRun_PolNum_split_inference.py
  setup.py
  xpsi/NestedSampler.py
  xpsi/Prior.py
  xpsi/__init__.py
  xpsi/tests/test_sampling.py
Labels: enhancement

#542 Made warning and error messages in Instrument more explicit
  xpsi/Instrument.py
Labels: Clean up crew 2025

#567 rayXpanda removal
  docs/source/HPC_systems.rst
  docs/source/install.rst
  setup.py
  xpsi/Everywhere.py
  xpsi/__init__.py
  xpsi/cellmesh/__init__.py
  xpsi/cellmesh/integrator.pyx
  xpsi/cellmesh/integratorIQU.pyx
  xpsi/cellmesh/integratorIQU_for_azimuthal_invariance.pyx
  xpsi/cellmesh/integratorIQU_for_azimuthal_invariance_split.pyx
  xpsi/cellmesh/integrator_for_azimuthal_invariance.pyx
  xpsi/cellmesh/integrator_for_azimuthal_invariance_split.pyx
  xpsi/cellmesh/integrator_for_time_invariance.pyx
  xpsi/cellmesh/rays.pxd
  xpsi/cellmesh/rays.pyx
  xpsi/include/rayXpanda/deflection.c
  xpsi/include/rayXpanda/deflection.h
  xpsi/include/rayXpanda/inversion.c
  xpsi/include/rayXpanda/inversion.h
Labels: Clean up crew 2025

#594 Update README.rst
  README.rst
Labels: documentation, Clean up crew 2025

#598 Update changelog.yml
  .github/workflows/changelog.yml
  changelog.d/598.attribution.rst
  changelog.d/598.changed.rst
Labels: documentation, enhancement, Clean up crew 2025

#600 Update README.rst badges
  README.rst
Labels: documentation, Clean up crew 2025, no-changelog-needed

#595 69 add docstrings and explainer comments to hotpyx numericalpyx
  changelog.d/595.attribution.rst
  changelog.d/595.changed.rst
  changelog.d/595.deprecated.rst
  xpsi/surface_radiation_field/hot_BB.pyx
  xpsi/surface_radiation_field/hot_BB_burst.pyx
  xpsi/surface_radiation_field/hot_Num2D.pyx
  xpsi/surface_radiation_field/hot_Num2D_split.pyx
  xpsi/surface_radiation_field/hot_Num4D.pyx
  xpsi/surface_radiation_field/hot_Num5D_split.pyx
  xpsi/surface_radiation_field/hot_wrapper.pyx
Labels: Clean up crew 2025

#606 Update install.rst
  docs/source/install.rst
Labels: no-changelog-needed

#607 Version and changelog update
  CHANGELOG.rst
  changelog.d/572.added.rst
  changelog.d/572.attribution.rst
  changelog.d/572.changed.rst
  changelog.d/572.summary.rst
  changelog.d/581.added.rst
  changelog.d/581.attribution.rst
  changelog.d/581.changed.rst
  changelog.d/585.attribution.rst
  changelog.d/585.changed.rst
  changelog.d/589.deprecated.rst
  changelog.d/590.added.rst
  changelog.d/590.attribution.rst
  changelog.d/590.fixed.rst
  changelog.d/591.attribution.rst
  changelog.d/591.fixed.rst
  changelog.d/595.attribution.rst
  changelog.d/595.changed.rst
  changelog.d/595.deprecated.rst
  changelog.d/598.attribution.rst
  changelog.d/598.changed.rst
  changelog.d/599.added.rst
  changelog.d/599.attribution.rst
  changelog.d/605.attribution.rst
  changelog.d/605.fixed.rst
  docs/source/conf.py
  setup.py
  xpsi/__init__.py
Labels: no-changelog-needed
